### ISSUE TITLE
Select and evaluate several alternative scikit-learn classifiers

### ISSUE THREAD

**Issue by BenKaehler** [BenKaehler/short-read-tax-assignment#3]
scikit-learn offers several different classifiers in different categories.

A reasonable overview of what's available and appropriate is [here](http://scikit-learn.org/stable/modules/multiclass.html). 

Would suggest that we should try at least BernoulliNB, SVCs and at least one of Decision Trees, Random Forests, Nearest Neighbors, Ridge Regression, or MLPClassifier.

Should also revisit feature selection. SelectPercentile doesn't seem to help for MultinomialNB, but it may work elsewhere and other feature selection techniques exist.

Also try TfidfTransformer for feature extraction.

All of this _should_ be possible using the general `fit-classifier` method in `feature-classifier`, but may require some fixes to the code.

**Comment by BenKaehler** [comment]
@GavinHuttley, is it worth consulting any of our computer science friends to get some advice on the best classifiers to try?

**Comment by GavinHuttley** [comment]
Yes

**Comment by BenKaehler** [comment]
Duplicate of #5
