### ISSUE TITLE
short-read-tax-assignment is a mouthful

### ISSUE THREAD

**Issue by BenKaehler** [BenKaehler/short-read-tax-assignment#7]
@gavinhuttley has suggested that we call it the SHARK.

@gregcaporaso seems naturally apprehensive.

How about the following backronym?

SHort read tAxonomy Rating for Classifiers?

So it would be SHARC. Close enough.

**Comment by gregcaporaso** [comment]
I'm good with a name change. I don't feel like the expanded acronym (or the original name) is very descriptive of what it is... 

Could we build something around _Marker Gene Taxonomic Classifier Assessment_?

When it comes down to it though, I'm happy with whatever you guys like.

**Comment by BenKaehler** [comment]
Sadly, it doesn't look like the SHARK has legs. How about

_Taxonomic Classifier Benchmark_?

At least that way it has a TLA.

**Comment by gregcaporaso** [comment]
That'd work for me.

**Comment by nbokulich** [comment]
TCB works for me — I think the name is adequately clear, which is important.

That said, here are some with catchier names, some more serious than others:

TACO MAkER TAxonomic Classification Of Marker dnA EvaluatoR
MANTeCA MArker dNa Taxonomic Classifier Assessment tool
MAGENTA MArker GENe Taxonomic Assessment tool
MAGNETIC MArker GeNE TaxonomIc Classification evaluator
TOMCAT   TaxonOMic Classifier Assessment Tool
TAX BREAK TAXonomic BenchmaRk to Evaluate Accuracy of Klassification
TAX CODE TAXonomic Classification Of Dna Evaluation tool
TAX CREdiT TAXonomic ClassifieR Evaluation Tool
TAX FREE TAXonomic FRamework for Evaluation of classifier Exactitude
USE TAX Utility for Standardized Evaluation of TAXonomy classifiers

**Comment by nbokulich** [comment]
@gregcaporaso @gavinhuttley

@BenKaehler and I have narrowed this down to three names. Shall we vote?

**MAGNETIC**          MArker GeNE TaxonomIc Classification evaluator
**TAX CREdiT**         TAXonomic ClassifieR Evaluation Tool
**TCB**                      Taxonomic Classifier Benchmark

**Comment by gregcaporaso** [comment]
> TAX CREdiT TAXonomic ClassifieR Evaluation Tool

I like that one - the acronym for this one seems to best fit what the tool does. One consideration that we often think of is whether it is relatively unique in Google results (hence *QIIME*), but I'm not sure that matters all that much this time since it's not really an end user tool that we're developing here.

**Comment by GavinHuttley** [comment]
I’m not sure my opinion should matter, so feel free to ignore. My pref is to keep it short.


TCB get’s my vote.

-----Original Message-----

**Comment by nbokulich** [comment]
Thanks @GavinHuttley ! Now that all votes are in: TAX CREdiT is the winner.
